### ISSUE TITLE
Create GitHub Release 1.0.0

### ISSUE THREAD

**Issue by favoyang** [bss1284/texteditor-unity-plugin#1]
Hey @bss1284,

Thanks for submitting to OpenUPM. Our build pipelines process git tags to publish new versions. You need  create GitHub Release 1.0.0 to make it work.

Learn more at https://openupm.com/docs/adding-upm-package.html#handling-a-repository-without-git-tag

**Comment by bss1284** [comment]
I saw your mail and applied it.

Thank you for your help.
ᐧ

2020년 3월 24일 (화) 오후 10:06, Favo Yang <notifications@github.com>님이 작성:
